# Generated by Django 4.0.5 on 2022-07-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('plano', models.CharField(max_length=30, verbose_name='Plano')),
                ('usuarios', models.CharField(max_length=50, verbose_name='Usuários')),
                ('armazenamento', models.CharField(max_length=50, verbose_name='Armazenamento')),
                ('suporte', models.CharField(max_length=50, verbose_name='Suporte')),
                ('atualizacoes', models.CharField(max_length=50, verbose_name='Atualizações')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.AlterField(
            model_name='feature',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Responsividade'), ('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-leaf', 'Sustentabilidade')], max_length=16, verbose_name='Icone'),
        ),
    ]
