# Generated by Django 4.0.5 on 2022-07-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plano_alter_feature_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Caixa'), ('lni-drop', 'Gota'), ('lni-star', 'Estrela')], default='lni-package', max_length=11, verbose_name='Icone'),
        ),
        migrations.AddField(
            model_name='plano',
            name='pagamento',
            field=models.CharField(choices=[('sem', 'Semanalmente'), ('mês', 'Mensalmente'), ('ano', 'Anualmente')], default='mês', max_length=3, verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='plano',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Preço (R$)'),
        ),
    ]
